rm(list = ls())
expr <- read.csv("GSE25066_symbol_avg_filtered_ordered.csv", header = TRUE, row.names = 1)
group <- read.table("GSE25066_group4.txt", header = TRUE, row.names = 1)
identical(rownames(group),colnames(expr))
save(expr, group, file = "GSE25066.rda")
rm(list = ls())
library(tidyverse)
library(limma)
load("GSE25066.rda")
group_list <- factor(group$group, levels = c("pCR","NonpCR"))
design <- model.matrix(~group_list)
fit <- lmFit(expr, design)
fit2 <- eBayes(fit)
dem <- topTable(fit2, coef = 2, number = Inf, adjust.method = "BH")
GSE25066_DEG <- na.omit(dem)
write.table(GSE25066_DEG, file = "GSE25066_diff.txt", sep = "\t", row.names = TRUE, col.names = NA, quote = FALSE)
