library(Seurat)
library(harmony)
library(tidyverse)
library(patchwork)
library(AUCell)
library(msigdbr)
set.seed(123)
seu_combined <- readRDS("seu_combined.rds")
qc_plots <- VlnPlot(seu_combined, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "orig.ident", layer = "counts", pt.size = 0)
ggsave("qc_metrics_before_filtering.pdf", qc_plots, width = 12, height = 6)
seu_combined <- subset(seu_combined, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 10)
qc_plots_after <- VlnPlot(seu_combined, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "orig.ident", layer = "counts", pt.size = 0)
ggsave("qc_metrics_after_filtering.pdf", qc_plots_after, width = 12, height = 6)
seu_combined <- NormalizeData(seu_combined)
seu_combined <- FindVariableFeatures(seu_combined, selection.method = "vst", nfeatures = 3000)
seu_combined <- ScaleData(seu_combined, vars.to.regress = "percent.mt")
saveRDS(seu_combined, file = "seu_combined_PCA_Before.rds")
seu_combined <- RunPCA(seu_combined, npcs = 50, verbose = FALSE)
seu_combined <- RunUMAP(seu_combined, reduction = "pca", dims = 1:30, reduction.name = "umap_pca")
p0 <- DimPlot(seu_combined, reduction = "umap_pca", group.by = "orig.ident")
ggsave("umap_before_harmony.pdf", p0, width = 8, height = 8)
p0_1 <- DimPlot(seu_combined, reduction = "umap_pca", group.by = "sample_id")
ggsave("p0_1.pdf", p0_1, width = 8, height = 8)
seu_pre_pcr <- subset(seu_combined, subset = treatment_stage == "Pre-treatment" & response %in% c("pCR", "NonpCR"))
p0_1_pre_pcr <- DimPlot(seu_pre_pcr, reduction = "umap_pca", group.by = "sample_id") + ggtitle("Pre-treatment (pCR and NonpCR) by sample_id - Before Harmony")
ggsave("p0_1_pre_pcr_before_harmony.pdf", p0_1_pre_pcr, width = 8, height = 8)
seu_combined <- RunHarmony(seu_combined, group.by.vars = "orig.ident")
seu_combined <- RunUMAP(seu_combined, reduction = "harmony", dims = 1:30, reduction.name = "umap_harmony")
p00 <- DimPlot(seu_combined, reduction = "umap_harmony", group.by = "orig.ident")
ggsave("umap_after_harmony.pdf", p00, width = 8, height = 8)
p00_1 <- DimPlot(seu_combined, reduction = "umap_harmony", group.by = "sample_id")
ggsave("p00_1.pdf", p00_1, width = 8, height = 8)
seu_pre_pcr1 <- subset(seu_combined, subset = treatment_stage == "Pre-treatment" & response %in% c("pCR", "NonpCR"))
p0_2_pre_pcr <- DimPlot(seu_pre_pcr1, reduction = "umap_harmony", group.by = "sample_id") + ggtitle("Pre-treatment (pCR and NonpCR) by sample_id - After Harmony")
ggsave("p0_2_pre_pcr_after_harmony.pdf", p0_2_pre_pcr, width = 8, height = 8)
seu_combined <- FindNeighbors(seu_combined, reduction = "harmony", dims = 1:30)
seu_combined <- FindClusters(seu_combined, resolution = 0.5)
seu_combined <- RunUMAP(seu_combined, reduction = "harmony", dims = 1:30, reduction.name = "umap")
p1 <- DimPlot(seu_combined, reduction = "umap", group.by = "seurat_clusters", label = TRUE)
p2 <- DimPlot(seu_combined, reduction = "umap", group.by = "orig.ident")
p3 <- DimPlot(seu_combined, reduction = "umap", group.by = "treatment_stage")
p4 <- DimPlot(seu_combined, reduction = "umap", group.by = "response")
combined_plot <- (p1 + p2) / (p3 + p4)
ggsave("umap_visualizations.pdf", combined_plot, width = 12, height = 10)
ggsave("seurat_clusters.pdf", p1, width = 8, height = 8)
ggsave("orig.ident.pdf", p2, width = 8, height = 8)
ggsave("treatment_stage.pdf", p3, width = 8, height = 8)
ggsave("response.pdf", p4, width = 8, height = 8)
saveRDS(seu_combined, file = "seu_combined_harmony.rds")
sessionInfo()
